#!/usr/bin/env node
require('dotenv').config();

if (!process.env.DEPLOY_TARGET) {
  console.error('You must pass the DEPLOY_TARGET environment variable.')
  process.exitCode = 1;
  process.exit();
}
console.log('Deploying to', process.env.DEPLOY_TARGET);

const spawn = require('child_process').spawn;
const rsync = spawn('rsync', ['-Pavz', 'public', process.env.DEPLOY_TARGET]);

rsync.stdout.on('data', data => process.stdout.write(data));
rsync.stderr.on('data', data => process.stderr.write(data));
rsync.on('close', code => {
  console.log('Child exited with', code, 'and stdout has been saved');
  process.exitCode = code;
});
